version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        must_exclude:
          regex: 'wip'
  - when: pull_request.*, issues.*
    validate:
      - do: title
        no_empty:
          enabled: true
          message: 'Please add a title...'
        must_exclude:
          regex: ^\[WIP\]
      - do: label
        must_exclude:
          regex: 'wip'
      - do: stale
        days: 14
        message: 'This is PR getting stale. Please follow up!  This is a friendly reminder to please resolve it. :-)'
        type: pull_request, issues

  - when: pull_request.*, pull_request_review.*, status.*, check_suite.*
    name: "Automatically merge pull requests once it passes all checks"
    validate: []
    pass:
      - do: merge
        merge_method: "squash"